# Generated by Django 6.0.4 on 2026-04-09 15:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterclass',
            name='online_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на трансляцию'),
        ),
        migrations.AddField(
            model_name='masterclass',
            name='participants',
            field=models.ManyToManyField(related_name='joined_masterclasses', through='main.Booking', through_fields=('masterclass', 'participant'), to=settings.AUTH_USER_MODEL, verbose_name='Участники'),
        ),
    ]
