# Generated by Django 6.0.4 on 2026-04-10 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_masterclass_online_link_masterclass_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterclass',
            name='program_file',
            field=models.FileField(blank=True, null=True, upload_to='programs/', verbose_name='Программа (PDF)'),
        ),
    ]
